Visium - simplify column names
drighelli/SpatialExperiment pull request #5
Opened 2020-08-31 19:26 UTC by lmweber

This one is a very minor suggestion - in the interests of making column names as short as possible, I suggest changing `pxl_col_in_fullres` and `pxl_row_in_fullres` to `pxl_col_fullres` and `pxl_row_fullres`. Having slightly shorter column names makes it a little bit easier to display the `spatialCoords` data frame in the console, since the columns are narrower.

(However feel free to ignore if you prefer the original names, or if they have been chosen for a specific reason, e.g. to match definitions in 10x Genomics raw data files.)

2020-09-09 08:17 UTC, drighelli commented
Thanks again @lmweber,

I started by using the original 10x Visium names, but for me, there is no particular for not modifying them!

I'll do it in the next release!

Dario

2020-09-09 08:40 UTC, drighelli requested changes
Please change the Visium Vignettes accordingly with the colnames changes you made!

Thanks! :)

2020-09-09 20:48 UTC, lmweber commented
Ah I see - I have tried out Space Ranger now too, and saw that these column names are in fact default column names from 10x Genomics.

I think then it is better not to change them. Better just to stick with the defaults that 10x Genomics has chosen, so that everything is consistent.

For future reference, the defaults are also shown here: https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/output/images

I'l cancel and close this pull request. Thanks for merging the other one.

2020-09-09 20:48 UTC, closed without merging

2020-09-10 08:52 UTC, drighelli commented
Thanks again for your help!!!

Dario